GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/6a295ca0c42971470b5e74a8

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5ldyIsImlkIjoiNmEzMjc4MWRhYzYwNmNhMjY0YTU4MDg0IiwiaWF0IjoxNzgxNjkyNDYxfQ.tygGVRMl7Qn_bHad5rNvLOAVh938LAgbz6ZLusku9qA

{
    "title": "Test Blog",
    "author": "New User",
    "url": "http://localhost/NEW",
    "likes": "2",
    "userId":"NewUser"
}
###
DELETE http://localhost:3003/api/blogs/6a2e8f392820ec405dd68e0c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0VXNlciIsImlkIjoiNmEyZDYzZmRkN2NiNzE4OTU2YzkxMmU5IiwiaWF0IjoxNzgxMzc0NTQzfQ.Gy0jEA6iLpmJJel5O3yDirtnvWUqiM26jHrCVhN_5mc

###
PUT http://localhost:3003/api/blogs/6a295f1b74ab100a85546d37
Content-Type: application/json

{
    "title": "One Blog",
    "author": "Mucahid-test",
    "url": "http://localhost:3003/api/blogs/6a295f1b74ab100a85546d37",
    "likes": "10"
}